<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wishlist</name>
   <tag></tag>
   <elementGuidId>8229a87e-7b02-49d2-a972-fc8935381eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.wishlist-header</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
